# Stage 1 frontend builder

FROM node:20-alpine As frontend-builder

WORKDIR /app

COPY ./frontend/package*.json /app

RUN npm install

COPY ./frontend /app

RUN npm run build

# stage-2  full-stack image

FROM node:20-alpine


WORKDIR /app

COPY ./backend/package*.json /app

RUN npm install

COPY ./backend /app

COPY --from=frontend-builder /app/dist /app/public

CMD ["node","server.js"]


